// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kimtfyvvmrjadnvbsjow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpbXRmeXZ2bXJqYWRudmJzam93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NTIxMjcsImV4cCI6MjA1OTQyODEyN30.gzqRKGcP3oWPmX7s2oPoO9dnd0C1mjDY3PLEjWeyJ5Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);